mod-name: FarFutureTechnologies
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - FarFutureTechnologies
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.4
    location: s3
  B9PartSwitch:
    version: 2.17.0
    location: s3
  CommunityResourcePack:
    version: 1.4.1
    location: s3
  DynamicBatteryStorage:
    tag: 2.1.10
    location: github
    repository: ChrisAdderley/DynamicBatteryStorage
  DeployableEngines:
    tag: 1.2.2
    location: github
    repository: ChrisAdderley/DeployableEngines
  CryoTanks:
    tag: 1.5.3
    location: github
    repository: ChrisAdderley/CryoTanks
  Waterfall:
    tag: 0.2.6
    location: github
    repository: post-kerbin-mining-corporation/Waterfall
  SystemHeat:
    tag: 0.1.5
    location: github
    repository: post-kerbin-mining-corporation/SystemHeat
  SpaceDust:
    tag: 0.1.5
    location: github
    repository: post-kerbin-mining-corporation/SpaceDust
deploy:
  SpaceDock:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 537  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 231670  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
